### ISSUE TITLE
Already installed packages but ImportError: Using `load_in_8bit=True`

### ISSUE THREAD

**Issue by sardetushar** [xhluca/llama-2-local-ui#1]
```
Building generator...
Traceback (most recent call last):
  File "C:\Users\TG2066\ai_projects\llama-2-local-ui\app.py", line 91, in <module>
    respond = build_generator(model_name=model_name, auth_token=auth_token)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TG2066\ai_projects\llama-2-local-ui\app.py", line 45, in build_generator
    model = LlamaForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TG2066\AppData\Local\anaconda3\envs\local-llama2\Lib\site-packages\transformers\modeling_utils.py", line 2401, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes`
```

pip freeze

```
**accelerate==0.22.0**
aiofiles==23.2.1
altair==5.0.1
annotated-types==0.5.0
anyio==3.7.1
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
attrs==23.1.0
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
**bitsandbytes==0.41.1**
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
colorama @ file:///C:/ci_311/colorama_1676422310965/work
contourpy==1.1.0
cycler==0.11.0
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
fastapi==0.102.0
ffmpy==0.3.1
filelock==3.12.2
fonttools==4.42.1
fsspec==2023.6.0
gradio==3.41.2
gradio_client==0.5.0
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
idna==3.4
importlib-resources==6.0.1
ipython @ file:///C:/b/abs_254uk73z5b/croot/ipython_1691532131313/work
jedi @ file:///C:/ci_311/jedi_1679427407646/work
Jinja2==3.1.2
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
kiwisolver==1.4.5
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline @ file:///C:/ci_311/matplotlib-inline_1676425798036/work
mpmath==1.3.0
networkx==3.1
numpy==1.25.2
orjson==3.9.5
packaging==23.1
pandas==2.0.3
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==10.0.0
prompt-toolkit @ file:///C:/ci_311/prompt-toolkit_1676425940920/work
psutil==5.9.5
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
pydantic==2.3.0
pydantic_core==2.6.3
pydub==0.25.1
Pygments @ file:///C:/b/abs_fay9dpq4n_/croot/pygments_1684279990574/work
pyparsing==3.0.9
python-dateutil==2.8.2
python-multipart==0.0.6
pytz==2023.3
PyYAML==6.0.1
referencing==0.30.2
regex==2023.8.8
requests==2.31.0
rpds-py==0.9.2
safetensors==0.3.3
scipy==1.11.2
semantic-version==2.10.0
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio==1.3.0
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
starlette==0.27.0
sympy==1.12
tokenizers==0.13.3
toolz==0.12.0
torch==2.0.1
tqdm==4.66.1
traitlets @ file:///C:/ci_311/traitlets_1676423290727/work
transformers==4.32.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4
uvicorn==0.23.2
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
websockets==11.0.3
```

**Comment by xhluca** [comment]
Try:
```
pip install bitsandbytes
```

**Comment by sardetushar** [comment]
I have already installed both bitsandbytes and accelerate

I have shared the pip freeze above

**Comment by xhluca** [comment]
@sardetushar I am not sure why this would happen if you did all the right steps. Since it's an issue with the Huggingface's LLaMa implementation, perhaps you can reopen this issue on the official huggingface/transformers repo?
